name: Django Rest App Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
        working-directory: ./backend-djangorest/api/src

      - name: Run tests
        run: |
          poetry run python manage.py test
        working-directory: ./backend-djangorest/api/src
      
      - name: Check deploy
        run: |
          poetry run python manage.py check --deploy
        working-directory: ./backend-djangorest/api/src
      
      - name: Check migrations
        run: |
          poetry run python manage.py makemigrations
        working-directory: ./backend-djangorest/api/src
        
      - name: Check build Docker Image
        run: |
          export APP_VERSION=$(grep -m 1 version src/pyproject.toml | tr -d '=' | cut -d' ' -f3 | tr -d '"' | tr -d '\n' | tr -d '\r')
          echo "Using version ${APP_VERSION}"
          IMAGE_TAG="${DJANGOREST_DOCKER_REPO_NAME}:${APP_VERSION}"
          docker build . -t ${IMAGE_TAG}
        env:
          DJANGOREST_DOCKER_REPO_NAME: ${{ secrets.DJANGOREST_DOCKER_REPO_NAME }}
        working-directory: ./backend-djangorest/api